sudo: required
dist: trusty

language: java

env:
  - ELASTICSEARCH_VERSION="1.3"
  - ELASTICSEARCH_VERSION="1.4"
  - ELASTICSEARCH_VERSION="1.5"
  - ELASTICSEARCH_VERSION="1.6"
  - ELASTICSEARCH_VERSION="1.7"
  - ELASTICSEARCH_VERSION="2.0"
  - ELASTICSEARCH_VERSION="2.1"
  - ELASTICSEARCH_VERSION="2.2"
  - ELASTICSEARCH_VERSION="2.3"
  - ELASTICSEARCH_VERSION="5.0"

matrix:
  allow_failures:
    - env: ELASTICSEARCH_VERSION="5.0"

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - docker run -d -p 127.0.0.1:9200:9200 elasticsearch:$ELASTICSEARCH_VERSION
  - pip install --user codecov

script:
  - gradle clean build integrationTest jacocoTestReport dist

after_success:
  - codecov

deploy:
    provider: releases
    api-key:
      secure: "R8Q/pW53GXC3fHVIe3fqhvweukdJNph0mtCV3vnMLj3Vrt8V33l8DgKvGfxrwh+bsd/v1lr01K5/rWijDsrWMd/8boAVcsJCIYwVS3C6dPxEb0lww5oThl1EHHM3/wM4FQLefbK8/KnTK8qWGSQmwLsX1M+Ehdy4QU9SfO28Ks4="
    file: "$(ls $TRAVIS_BUILD_DIR/build/distributions/newrelic-elasticsearch-plugin*.tar.gz | head -n 1)"
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
        condition:
          - $TRAVIS_JDK_VERSION = oraclejdk7
          - $ELASTICSEARCH_VERSION = "2.0"
