sudo: required
dist: trusty

language: java

env:
  - ELASTICSEARCH_VERSION="1.3"
  - ELASTICSEARCH_VERSION="1.7-alpine"
  - ELASTICSEARCH_VERSION="2.4-alpine"
  - ELASTICSEARCH_VERSION="5-alpine"
  - ELASTICSEARCH_VERSION="6.6.1"

jdk:
  - openjdk8

before_install:
  - sudo sysctl -w vm.max_map_count=262144
  - docker run -d -p 127.0.0.1:9200:9200 elasticsearch:$ELASTICSEARCH_VERSION
  - pip install --user codecov

script:
  - gradle clean build integrationTest jacocoTestReport dist

after_success:
  - codecov

deploy:
    provider: releases
    api-key:
      secure: "R8Q/pW53GXC3fHVIe3fqhvweukdJNph0mtCV3vnMLj3Vrt8V33l8DgKvGfxrwh+bsd/v1lr01K5/rWijDsrWMd/8boAVcsJCIYwVS3C6dPxEb0lww5oThl1EHHM3/wM4FQLefbK8/KnTK8qWGSQmwLsX1M+Ehdy4QU9SfO28Ks4="
    file: "$(ls $TRAVIS_BUILD_DIR/build/distributions/newrelic-elasticsearch-plugin*.tar.gz | head -n 1)"
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
        condition:
          - $TRAVIS_JDK_VERSION = openjdk8
          - $ELASTICSEARCH_VERSION = "6.6.1"
